CREATE TABLE IF NOT EXISTS quotes (
    id SERIAL PRIMARY KEY,
    quote_id VARCHAR(50) UNIQUE NOT NULL,
    dealer_name VARCHAR(255) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(50) NOT NULL,
    customer_address TEXT,
    customer_city VARCHAR(100),
    customer_state VARCHAR(100),
    customer_zip VARCHAR(20),
    customer_country VARCHAR(100),
    boat_model VARCHAR(255) NOT NULL,
    engine_package VARCHAR(255) NOT NULL,
    hull_color VARCHAR(255) NOT NULL,
    upholstery_package TEXT,
    additional_options TEXT[],
    payment_method VARCHAR(100),
    deposit_amount DECIMAL(10,2),
    additional_notes TEXT,
    quote_date DATE NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    total_usd DECIMAL(10,2) NOT NULL,
    total_brl DECIMAL(10,2) NOT NULL,
    valid_until DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
